# Generated by Django 5.2.4 on 2025-07-22 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanchonete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lanchonetes/logos/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tempo_estimado', models.PositiveIntegerField(default=30, help_text='Tempo em minutos')),
                ('raio_entrega', models.DecimalField(decimal_places=1, default=5, help_text='Raio em km', max_digits=5)),
                ('dias_funcionamento', models.CharField(help_text='Dias separados por vírgula', max_length=100)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('dinheiro', models.BooleanField(default=True)),
                ('cartao_credito', models.BooleanField(default=True)),
                ('cartao_debito', models.BooleanField(default=True)),
                ('pix', models.BooleanField(default=True)),
                ('vale_refeicao', models.BooleanField(default=False)),
                ('chave_pix', models.CharField(blank=True, max_length=100)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanchonetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lanchonete',
                'verbose_name_plural': 'Lanchonetes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=15)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('lanchonete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.lanchonete')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('lanchonete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.lanchonete')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_entrega', models.CharField(choices=[('balcao', 'Balcão'), ('delivery', 'Delivery'), ('mesa', 'Mesa')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('preparando', 'Preparando'), ('pronto', 'Pronto'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('lanchonete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.lanchonete')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category')),
                ('lanchonete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.lanchonete')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioLanchonete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proprietario', 'Proprietário'), ('administrador', 'Administrador'), ('funcionario', 'Funcionário')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_vinculacao', models.DateTimeField(auto_now_add=True)),
                ('lanchonete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lanchonete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário da Lanchonete',
                'verbose_name_plural': 'Usuários das Lanchonetes',
                'unique_together': {('usuario', 'lanchonete')},
            },
        ),
    ]
