# Generated by Django 5.0.2 on 2025-05-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_taxa_entrega_pedido_tipo_entrega_pedido_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lanchonete', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tempo_estimado', models.PositiveIntegerField(default=30)),
                ('raio_entrega', models.DecimalField(decimal_places=1, default=5, max_digits=5)),
                ('dias_funcionamento', models.CharField(help_text='Dias separados por vírgula', max_length=100)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('dinheiro', models.BooleanField(default=True)),
                ('cartao_credito', models.BooleanField(default=True)),
                ('cartao_debito', models.BooleanField(default=True)),
                ('pix', models.BooleanField(default=True)),
                ('vale_refeicao', models.BooleanField(default=False)),
                ('chave_pix', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
