services:
  web:
    build: .
    container_name: lanchonete # lachonete
    hostname: lanchonete
    volumes:
      - .:/app
    ports:
      - "9999:9999"
    environment:
      - DJANGO_SECRET_KEY=chave-super-secreta
      - DJANGO_DEBUG=1
      - DJANGO_SETTINGS_MODULE=lanchonete.settings 
      - DJANGO_ALLOWED_HOSTS=0.0.0.0,localhost,127.0.0.1
      - DJANGO_CSRF_ORIGINS=http://localhost,http://127.0.0.1
      - DJANGO_CORS_ORIGINS=http://localhost,http://127.0.0.1