services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=lanchonete_db
      - POSTGRES_USER=lanchonete_user
      - POSTGRES_PASSWORD=lanchonete_password
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=lanchonete.settings_local
      - POSTGRES_DB=lanchonete_db
      - POSTGRES_USER=lanchonete_user
      - POSTGRES_PASSWORD=lanchonete_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000