services:
  web:
    build: .
    container_name: lachonete
    hostname: lanchonete
    volumes:
      - .:/app
    ports:
      - "9999:9999"
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_SETTINGS_MODULE=lanchonete.settings 