FROM python:3.12-slim

# Configurações de ambiente
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Instalar dependências do sistema
RUN apt-get update \
    && apt-get install -y python3-dev postgresql-client libpq-dev build-essential pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY requirements.txt .

# Instalar dependências Python
RUN pip install --upgrade pip && \ 
    pip install --no-cache-dir -r requirements.txt

# Copiar arquivos do projeto
COPY . /usr/src/app/

# Coletar arquivos estáticos
RUN python manage.py collectstatic --noinput

# Inicialização rápida para desenvolvimento
CMD ["sh", "-c", "python manage.py migrate --noinput && echo 'Iniciando Django runserver na porta 8000...' && python manage.py runserver 0.0.0.0:8000"]

EXPOSE 8000 