services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lanchonete-dev
    hostname: lanchonete-dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=chave-super-secreta
      - DJANGO_DEBUG=1
      - DJANGO_SETTINGS_MODULE=lanchonete.settings 
      - DJANGO_ALLOWED_HOSTS=0.0.0.0,localhost,127.0.0.1
      - DJANGO_CSRF_ORIGINS=http://localhost,http://127.0.0.1
      - DJANGO_CORS_ORIGINS=http://localhost,http://127.0.0.1 