[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn lanchonete.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120 --keep-alive 2"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "lanchonete-web" 