[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn lanchonete.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
DJANGO_SETTINGS_MODULE = "lanchonete.settings.prod"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"