[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py setup_initial_data && gunicorn lanchonete.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --worker-class sync --timeout 120"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
DJANGO_SETTINGS_MODULE = "lanchonete.settings.prod"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"