# Generated by Django 5.0.2 on 2025-08-07 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lanchonete', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tempo_estimado', models.PositiveIntegerField(default=30)),
                ('raio_entrega', models.DecimalField(decimal_places=1, default=5, max_digits=5)),
                ('dias_funcionamento', models.CharField(help_text='Dias separados por vírgula', max_length=100)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('dinheiro', models.BooleanField(default=True)),
                ('cartao_credito', models.BooleanField(default=True)),
                ('cartao_debito', models.BooleanField(default=True)),
                ('pix', models.BooleanField(default=True)),
                ('vale_refeicao', models.BooleanField(default=False)),
                ('chave_pix', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='RJ', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='S/N', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('balcao', 'Balcão'), ('delivery', 'Delivery'), ('mesa', 'Mesa')], default='balcao', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
