# Generated by Django 5.0.2 on 2025-08-07 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao_cliente_bairro_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='chave_pix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cnpj',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='dias_funcionamento',
            field=models.CharField(default='', help_text='Dias separados por vírgula', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='endereco',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='horario_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='horario_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_lanchonete',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
