# Generated by Django 5.0.2 on 2025-08-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanchonete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('cnpj', models.CharField(default='', max_length=20, unique=True)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('endereco', models.CharField(default='', max_length=255)),
                ('numero', models.CharField(default='S/N', max_length=10)),
                ('bairro', models.CharField(default='Centro', max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='RJ', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lanchonetes/logos/')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tempo_estimado', models.PositiveIntegerField(default=30, help_text='Tempo em minutos')),
                ('raio_entrega', models.DecimalField(decimal_places=1, default=5, help_text='Raio em km', max_digits=5)),
                ('dias_funcionamento', models.CharField(default='', help_text='Dias separados por vírgula', max_length=100)),
                ('horario_abertura', models.TimeField(blank=True, null=True)),
                ('horario_fechamento', models.TimeField(blank=True, null=True)),
                ('dinheiro', models.BooleanField(default=True)),
                ('cartao_credito', models.BooleanField(default=True)),
                ('cartao_debito', models.BooleanField(default=True)),
                ('pix', models.BooleanField(default=True)),
                ('vale_refeicao', models.BooleanField(default=False)),
                ('chave_pix', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lanchonete',
                'verbose_name_plural': 'Lanchonetes',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='lanchonete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.lanchonete'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lanchonete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.lanchonete'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lanchonete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.lanchonete'),
        ),
        migrations.AddField(
            model_name='product',
            name='lanchonete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.lanchonete'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('lanchonete', 'code')},
        ),
    ]
