# Generated by Django 5.0.2 on 2025-08-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lanchonete_alter_product_code_category_lanchonete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='cartao_credito',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='cartao_debito',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='dinheiro',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='pix',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='vale_refeicao',
        ),
        migrations.RemoveField(
            model_name='lanchonete',
            name='cartao_credito',
        ),
        migrations.RemoveField(
            model_name='lanchonete',
            name='cartao_debito',
        ),
        migrations.RemoveField(
            model_name='lanchonete',
            name='dinheiro',
        ),
        migrations.RemoveField(
            model_name='lanchonete',
            name='vale_refeicao',
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='raio_entrega',
            field=models.DecimalField(decimal_places=1, default=5, help_text='Raio em km', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='tempo_estimado',
            field=models.PositiveIntegerField(default=30, help_text='Tempo em minutos'),
        ),
    ]
