# Generated by Django 5.0.2 on 2025-08-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='taxa_entrega',
        ),
        migrations.AddField(
            model_name='lanchonete',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='cep',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='lanchonetes/'),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='raio_entrega',
            field=models.DecimalField(decimal_places=1, default=5, help_text='Raio de atendimento em km', max_digits=5),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('balcao', 'Balcão'), ('entrega', 'Entrega')], default='balcao', max_length=10),
        ),
    ]
