# Generated by Django 5.0.2 on 2025-08-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_configuracao_remove_pedido_taxa_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanchonete',
            name='dias_funcionamento',
            field=models.CharField(blank=True, default='', help_text='Dias separados por vírgula', max_length=100, null=True),
        ),
    ]
